MODEL:
  NAME: 'transformer'
  DEVICE_ID: "('0')"
  PRETRAIN_PATH: 'pretrained/vit_transreid_msmt.pth'
  PRETRAIN_CHOICE: 'self'
  STRIDE_SIZE: [12, 12]
  SIE_CAMERA: True
  SIE_VIEW: False
  JPM: True
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  COS_LAYER: False
  NECK: 'bnneck'
  LAST_STRIDE: 1
  ID_LOSS_TYPE: 'softmax'
  SIE_COE: 3.0
  DROP_PATH: 0.1
  DROP_OUT: 0.0
  ATT_DROP_RATE: 0.0
  SHUFFLE_GROUP: 2
  SHIFT_NUM: 5
  DEVIDE_LENGTH: 4
  RE_ARRANGE: True

DATASETS:
  NAMES: 'mot20'
  ROOT_DIR: 'data/MOT20'

DATALOADER:
  NUM_WORKERS: 4
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  RE_PROB: 0.5

SOLVER:
  MAX_EPOCHS: 60
  BASE_LR: 0.0008
  WEIGHT_DECAY: 0.00004
  IMS_PER_BATCH: 32
  WARMUP_EPOCHS: 10
  CHECKPOINT_PERIOD: 10
  COSINE_SCALE: 30
  COSINE_MARGIN: 0.2

TEST:
  NECK_FEAT: 'after'
  IMS_PER_BATCH: 32

OUTPUT_DIR: '../logs/mot20_seq02_msmt_transreid'